### ISSUE TITLE
Error while running CTAP2 tests

### ISSUE THREAD

**Issue by ieugeni** [fido-alliance/conformance-tool-issues#117]
The test tools fails when trying to write to HID device. Is the same error like for U2F tests.

![ctap2_testtool_fails](https://user-images.githubusercontent.com/29768798/33762883-ff75ea46-dc16-11e7-8f41-5e5262223057.PNG)

**Comment by valentinifx** [comment]
Hi,

**Same as for another reported issue (U2F):**
_https://github.com/fido-alliance/conformance-tool-issues/issues/4_


In version 0.9.301, I have fixed the "Error: Cannot write to HID device" according to hidapi bug fix suggestion mentioned inside the README.md.
 Quote:
 "BUG: if the first byte of a write() is 0x00, you may need to prepend an extra 0x00 due to a bug in hidapi (see issue #187)"

Fix implementation:
1.For U2F: File u2fv11dep.js, line 115: 

added "buffer.unshift(0);" before "device.write(buffer);"

2.For CTAP2: File ctap2dep.js, line 157: 

added "buffer.unshift(0);" before "device.write(buffer);"


It didn't seem necessary to also modify "sendHIDBufferSync" (in both u2fv11dep.js and ctap2dep.js) the same way...
 I am using a 64-bit Windows machine. Would it make sense to try to have this byte (0x00) insertion (report ID) always implemented in the application?

Thanks,
 Valentin

**Comment by herrjemand** [comment]
@ieugeni @valentinifx Actually on windows it affects any buffer that is being sent.

It is resolved in the newest build. Will upload it tonight.
