### ISSUE TITLE
Errors while running U2F tests

### ISSUE THREAD

**Issue by ieugeni** [fido-alliance/conformance-tool-issues#4]
Receive errors when running U2F v1.1 on FIDO Conformance Tools v0.9.5. Please see attached screenshot. The U2F token is inserted in the USB port and is working with the old U2F test tool.

![fido_conformance_tools_u2f_error](https://user-images.githubusercontent.com/29768798/31821817-038e954e-b5af-11e7-9352-319d2260ab0f.png)

**Comment by herrjemand** [comment]
It looks like your authenticator did not return response in time. Could you run these tests with few alternative authenticators, and tell me if the result stay the same?

Regards. Yuriy

**Comment by eugenInfineon** [comment]
I've also tried with a different authenticator from another vendow and still have the same issue. Even worse, something after starting the HID tests I'm receiving a blank window inside test tool.

**Comment by herrjemand** [comment]
Hey @eugenInfineon. I am working on finding resolution for the blank screen issue right now. Will get back to you shortly.

**Comment by herrjemand** [comment]
Hey @eugenInfineon. The new version should resolve blankscreen issues

**Comment by eugenInfineon** [comment]
Hi Yuriy. I tried 0.9.14 version but I still have the same behavior, but different error code now for the first token.
![u2f_v1_1_testtool_0_9_14_error](https://user-images.githubusercontent.com/29768798/32382922-3bedc0c0-c0bf-11e7-9d5a-dc7073a8a245.PNG)

**Comment by valentinifx** [comment]
Hi,

In version 0.9.301, I have fixed the "Error: Cannot write to HID device" according to hidapi bug fix suggestion mentioned inside the README.md.
Quote:
"BUG: if the first byte of a `write()` is 0x00, you may need to prepend an extra 0x00 due to a bug in hidapi (see issue #187)"

Fix implementation:
1. For U2F: File u2fv11dep.js, line 115:
    > added "buffer.unshift(0);" before "device.write(buffer);"
2. For CTAP2: File ctap2dep.js, line 157:
    > added "buffer.unshift(0);" before "device.write(buffer);"

It didn't seem necessary to also modify "sendHIDBufferSync" (in both u2fv11dep.js and ctap2dep.js) the same way...
I am using a 64-bit Windows machine. Would it make sense to try to have this byte (0x00) insertion (report ID) always implemented in the application?

Thanks,
Valentin

**Comment by herrjemand** [comment]
Resolved
